### ISSUE TITLE
CosmicNvim repo has permission denied

### ISSUE THREAD

**Issue by nelson777** [CosmicNvim/CosmicNvim#101]
I was trying to give CosmicNvim a try but I'm getting permission denied when I try to clone the repo. Am I missing something or it's some problem with the repo ?

```
> git clone git@github.com:mattleong/CosmicNvim.git
Cloning into 'CosmicNvim'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by prrockzed** [comment]
I guess this is not a problem with the repo.
Try these links for reference
1. https://stackoverflow.com/questions/57734669/gitgithub-com-permission-denied-publickey
2. https://stackoverflow.com/questions/2643502/git-how-to-solve-permission-denied-publickey-error-when-using-git/42641637#42641637

Or else just clone the repo using http rather than using ssh.
