### ISSUE TITLE
Version error

### ISSUE THREAD

**Issue by BtAbdul** [CosmicNvim/CosmicNvim#104]
I'm got error while installing CosmicNvim.

My nvim --version
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.0-beta3

Its says "Need Neovim V0.10+ in order to run CosmicNvim

Here is screen shot
![IMG_20231021_181952](https://github.com/CosmicNvim/CosmicNvim/assets/46757797/c630d48a-3904-4f6b-9360-093b0c7dd08e)

**Comment by maxiim3** [comment]
same here.

**Comment by BtAbdul** [comment]
> same here.

you can run it by following this

goto
`cd ~/.config/nvim/`
Make sure there is init.lua file 
`ls`
then open it any editor nano or nvim 
`nvim init.lua`

and comment or delete this line, i just comment it
![IMG_20231023_000142](https://github.com/CosmicNvim/CosmicNvim/assets/46757797/9b051fda-2345-4ba8-816d-94b60d58211e)

now close nvim and run again by `nvim`

**Comment by mattleong** [comment]
For CosmicNvim, there's a hard requirement for neovim v0.10, i.e. nightly.

However, I may consider stepping the required version down and only allowing v0.10 features if running the correct neovim version.

**Comment by PiotrOwsiak** [comment]
@mattleong it would be less confusing if this was clearly stated in the install instructions as a prerequisite

**Comment by mattleong** [comment]
> @mattleong it would be less confusing if this was clearly stated in the install instructions as a prerequisite

Is there a better place than where it has been for quite some time? I'm fairly sure this is already what you asked for, verbatim. 😉

![image](https://github.com/CosmicNvim/CosmicNvim/assets/3721204/ad7c8a3c-3870-462e-99b7-62701cae0798)

**Comment by PiotrOwsiak** [comment]
@mattleong sorry for not being clear enough, I meant that it would be good if it was clearly stated that the version required is a nightly cause right now it does look like a potential mistake and people who use package managers may not even know exactly which version they are using but if you state it is nightly then it will be pretty clear to them that they don't meet the requirements if they use a package manager and just update to latest official release every now and then.
What happened in my case was that I do not track every new release and don't even know what it the latest so I saw that Neovim +0.10.0 is required which I thought, well I may already have it and if not then I'll just quick upgrade using brew buuut it turned out I cannot just upgrade cause it is nightly which makes things far more complex and for me personally I prefer to wait rather than spent extra time on my work machine fiddling with stuff. I guess if it was clear to me that Cosmic requires nightly I would not even try it at this point, so IMHO if you could add this one extra word to the pre-requisites it would really help.

**Comment by mattleong** [comment]
@PiotrOwsiak Done 👍
