### ISSUE TITLE
wrong indentation with import actions

### ISSUE THREAD

**Issue by andersonba** [CosmicNvim/CosmicNvim#32]
First, great job! I'm really excited about this project. Thank you!
Second, I don't know where to report this issue, if it's something specific to the LSP provider or not... anyway :)

Every time I run the "organize imports", "import current" or "import all", it ends up generating inconsistency with the indention.
I have configured the tab size to 2 (_tabstop_, _shiftwidth_, _softtabstop_...) but the commands do not respect it. Thereafter, when I save the file, the auto-format fix all.  

See:

https://user-images.githubusercontent.com/1501013/144976465-4ae50930-e85e-4283-9e9c-1bf0c2db74f4.mp4

Would you have any idea what it could be or where I should look? Thanks!

**Comment by mattleong** [comment]
Hmm.. after a little bit of digging in [`nvim-lsp-ts-utils`](https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils/blob/main/lua/nvim-lsp-ts-utils/organize-imports.lua) (the plugin that enables that functionality). I'm not exactly sure what can be done on Cosmic's side since all it does is make a simple request to tsserver.

I'd suggest raising this issue there and seeing if there is a workaround/fix I'm not finding.

**Comment by andersonba** [comment]
https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils/discussions/95

we'll probably have to wait for something on the tsserver side
thanks @mattleong
